-- By Maler
livery = {
	{"P51D_FUZ_FRONT", 0 ,"p51D_DIF_Fuz_Front_GUNFIGHTER",false};
	{"P51D_FUZ_REAR", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_WING_L", 0 ,"p51D_DIF_L_Wing_GUNFIGHTER",false};
	{"P51D_WING_R", 0 ,"p51D_DIF_R_Wing_GUNFIGHTER",false};
        {"P51D_FUZ_FRONT", 1 ,"p51D_NRML_GUNFIGHTER_Fuz_Front",false};
        {"P51D_FUZ_REAR", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_WING_L", 1 ,"p51D_NRML_GUNFIGHTER_L_Wing",false};
        {"P51D_WING_R", 1 ,"p51D_NRML_GUNFIGHTER_R_Wing",false};
	{"P51D_FUZ_FRONT", 2 ,"p51D_SPEC_Fuz_Front_GUNFIGHTER",false};
	{"P51D_FUZ_REAR", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_WING_L", 2 ,"p51D_SPEC_L_Wing_GUNFIGHTER",false};
	{"P51D_WING_R", 2 ,"p51D_SPEC_R_Wing_GUNFIGHTER",false};



	{"P51D_FUZ_FRONT", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Front_GUNFIGHTER_RoughMet",false};
	{"P51D_FUZ_REAR", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_WING_L", ROUGHNESS_METALLIC ,"P51D_DIF_L_Wing_GUNFIGHTER_RoughMet",false};
	{"P51D_WING_R", ROUGHNESS_METALLIC ,"P51D_DIF_R_Wing_GUNFIGHTER_RoughMet",false};
	{"P51D_BORT_NUMBER_COCPIT_01", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Front_GUNFIGHTER_RoughMet",false};
	{"P51D_BORT_NUMBER_FRONT_10", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Front_GUNFIGHTER_RoughMet",false};
	{"P51D_BORT_NUMBER_FRONT_01", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Front_GUNFIGHTER_RoughMet",false};
	{"P51D_BORT_NUMBER_FRONT-2_10", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Front_GUNFIGHTER_RoughMet",false};
	{"P51D_BORT_NUMBER_FRONT-2_01", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Front_GUNFIGHTER_RoughMet",false};
	{"P51D_BORT_NUMBER_REAR-2_10", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_BORT_NUMBER_REAR-2_01", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_BORT_NUMBER_TAIL_01", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_BORT_NUMBER_FIN_01", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_SERIAL_NUMBER_L_001", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_SERIAL_NUMBER_L_010", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_SERIAL_NUMBER_L_100", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_SERIAL_NUMBER_R_001", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_SERIAL_NUMBER_R_010", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};
	{"P51D_SERIAL_NUMBER_R_100", ROUGHNESS_METALLIC ,"P51D_DIF_Fuz_Rear_GUNFIGHTER_RoughMet",false};


	{"P51D_BORT_NUMBER_COCPIT_01", 0 ,"p51D_DIF_Fuz_Front_GUNFIGHTER",false};
        {"P51D_BORT_NUMBER_COCPIT_01", 1 ,"p51D_NRML_GUNFIGHTER_Fuz_Front",false};
	{"P51D_BORT_NUMBER_COCPIT_01", 2 ,"p51D_SPEC_Fuz_Front_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_COCPIT_01", DECAL ,"empty",true};



	{"P51D_BORT_NUMBER_FRONT_10", 0 ,"p51D_DIF_Fuz_Front_GUNFIGHTER",false};
        {"P51D_BORT_NUMBER_FRONT_10", 1 ,"p51D_NRML_GUNFIGHTER_Fuz_Front",false};
	{"P51D_BORT_NUMBER_FRONT_10", 2 ,"p51D_SPEC_Fuz_Front_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_FRONT_10", DECAL ,"empty",true};

	{"P51D_BORT_NUMBER_FRONT_01", 0 ,"p51D_DIF_Fuz_Front_GUNFIGHTER",false};
        {"P51D_BORT_NUMBER_FRONT_01", 1 ,"p51D_NRML_GUNFIGHTER_Fuz_Front",false};
	{"P51D_BORT_NUMBER_FRONT_01", 2 ,"p51D_SPEC_Fuz_Front_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_FRONT_01", DECAL ,"empty",true};


	{"P51D_BORT_NUMBER_FRONT-2_10", 0 ,"p51D_DIF_Fuz_Front_GUNFIGHTER",false};
        {"P51D_BORT_NUMBER_FRONT-2_10", 1 ,"p51D_NRML_GUNFIGHTER_Fuz_Front",false};
	{"P51D_BORT_NUMBER_FRONT-2_10", 2 ,"p51D_SPEC_Fuz_Front_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_FRONT-2_10", DECAL ,"empty",true};

	{"P51D_BORT_NUMBER_FRONT-2_01", 0 ,"p51D_DIF_Fuz_Front_GUNFIGHTER",false};
        {"P51D_BORT_NUMBER_FRONT-2_01", 1 ,"p51D_NRML_GUNFIGHTER_Fuz_Front",false};
	{"P51D_BORT_NUMBER_FRONT-2_01", 2 ,"p51D_SPEC_Fuz_Front_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_FRONT-2_01", DECAL ,"empty",true};

	{"P51D_BORT_NUMBER_REAR-2_10", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_BORT_NUMBER_REAR-2_10", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_REAR-2_10", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_REAR-2_10", DECAL ,"empty",true};

	{"P51D_BORT_NUMBER_REAR-2_01", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_BORT_NUMBER_REAR-2_01", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_REAR-2_01", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_REAR-2_01", DECAL ,"empty",true};



	{"P51D_BORT_NUMBER_TAIL_01", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_BORT_NUMBER_TAIL_01", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_TAIL_01", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_TAIL_01", DECAL ,"empty",true};

	{"P51D_BORT_NUMBER_FIN_01", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_BORT_NUMBER_FIN_01", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_FIN_01", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_BORT_NUMBER_FIN_01", DECAL ,"empty",true};



	{"P51D_SERIAL_NUMBER_L_001", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_SERIAL_NUMBER_L_001", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
 	{"P51D_SERIAL_NUMBER_L_001", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_L_001", DECAL ,"empty",true};

	{"P51D_SERIAL_NUMBER_L_010", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_SERIAL_NUMBER_L_010", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_L_010", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_L_010", DECAL ,"empty",true};

	{"P51D_SERIAL_NUMBER_L_100", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_SERIAL_NUMBER_L_100", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_L_100", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_L_100", DECAL ,"empty",true};

	{"P51D_SERIAL_NUMBER_R_001", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_SERIAL_NUMBER_R_001", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_R_001", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_R_001", DECAL ,"empty",true};

	{"P51D_SERIAL_NUMBER_R_010", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_SERIAL_NUMBER_R_010", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_R_010", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_R_010", DECAL ,"empty",true};

	{"P51D_SERIAL_NUMBER_R_100", 0 ,"p51D_DIF_Fuz_Rear_GUNFIGHTER",false};
        {"P51D_SERIAL_NUMBER_R_100", 1 ,"P51D_NRML_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_R_100", 2 ,"p51D_SPEC_Fuz_Rear_GUNFIGHTER",false};
	{"P51D_SERIAL_NUMBER_R_100", DECAL ,"empty",true};

	{"pilot_P51_helmet_A", 0 ,"pilot_P51_helmet_gunfighter",false};
	{"pilot_P51_patch_USAF", 0 ,"empty",false};
	{"pilot_P51", 0 ,"empty",false};
}
name = "TF-51 Gunfighter"
