livery = {
	{"fuz-center", 0, "SU39-PAINT1-DEF-01_gre", false},
	{"wings", 0, "SU39-PAINT2-DEF-01_gre", false},
	{"SU39-PAINT2bis-DEF-01", 0, "SU39-PAINT2bis-DEF-01_gre", false},
	{"fuz-tail & fin", 0, "SU39-PAINT3-DEF-01_gre", false},
	{"tail & stab", 0, "SU39-PAINT4-DEF-01_gre", false},
	{"brake-L", 0, "SU39-PAINT5-L-DEF-01_gre", false},
	{"brake-R", 0, "SU39-PAINT5-R-DEF-01_gre", false},
	{"fuz-nose-steel", 0, "SU39-PAINT6-DEF-01_gre", false},
	{"SU-39-PILON", 0, "SU39-PILON-PAINT-DEF-01_gre", false},
	{"PILON_2_Su-39", 0, "SU39-PILON-2-PAINT-DEF-01_gre", false},
	{"numbers", 0, "rus-code-numbers-ver1-BwW-X.tga_gre", false},
	{"PylonsSu-25T1", 0, "Su-25TPylon_gre", false},
	{"gear-rubber", 0, "SU39-PAINT7-DEF-01_gre", false},
	{"gear-metal", 0, "SU39-PAINT7-DEF-01_gre", false},
	{"gear-steel", 0, "SU39-PAINT7-DEF-01_gre", false},
	{"gear-bay", 0, "SU39-PAINT8-DEF-01_gre", false},
	{"pylon25lateral", 0, "Lateral25TPylon_gre.bmp", true},
	{"RUS-PILOT", 0, "rus-pilot-2-gr.bmp", true},
	{"RUS-HELMET", 0, "rus-helmet-gr.bmp", true},
}
name = "Hellenic Airforce (Fictional)"
